### ISSUE TITLE
Oprava DSP

### ISSUE THREAD

**Issue by vairad** [vairad/zcu-zswi#10]
Je třeba opravit DSP ve wiki, dle připomínek z Iterace.

Štěpáne mohl bys sem hodit ty body, co je třeba opravit.
Deni oprav prosím tu výslednou specifikaci..

**Comment by Thoronir42** [comment]
Při průběžné kontrole DSP byly zaznamenány následující body:
### Kontext systému 
 * Ve spojitosti s bodem " 1.4 Rozsah projektu " by bylo dobré, kdyby se alespoň částečně přesunul obsah tohoto bodu do úvodu

### 2.4 Odkazy na verze 
 * Zde je třeba připsat odkazy na verze platforem a použitého software..
  * Arduino
   * arduino http://arduino.cc/en/Main/ArduinoBoardUno
   * eHealth http://www.cooking-hacks.com/documentation/tutorials/ehealth-biometric-sensor-platform-arduino-raspberry-pi-medical
   * bluetooth http://arduino.cc/en/Main/ArduinoBoardBT
  * desktop
   * bluetooth [ vykoumat / optat se ]
   * qt http://www.qt.io/qt5-4/
 * Také zde byla připomínka na desktop-nezávislý na platformě => nezávislý na OS

### Funkce systému 
 * rozdělení na opravdu dílčí úlohy (například 3.2.3 požadavek 2 "základní zobrazení / uložení získaných dat" rozdělit na dva požadavky)

### "robustnost aplikace"
 * klidně napsat že bude blbo-odolná
 * pokusit se nahradit případné další buzz-wordy

### bezpečnostní / mimofunkční požadavky
 * mluvilo se o bezpečnosti uživatelů, tzn něco ve smyslu že systém aplikace, arudina a senzorů neohrožuje zdraví uživatele

### průběžné doplňování slovníčku
jednoduché popisy nebo rozepsání a přeložení zkratek
 * např GUI, Qt, e-Health
