### ISSUE TITLE
Funkční smyčka

### ISSUE THREAD

**Issue by vairad** [vairad/zcu-zswi#11]
Je třeba vytvořit a vyzkoušet smyčku senzorů. (Abychom měli jasný formát dat)

**Comment by Thoronir42** [comment]
Vyměnil jsem ukázkový příklad, ze kterého vychází čtecí a odesílací smyčka aruina za bluetoothový příklad (předtím jsem omylem vybral příklad využívající wi-fi). Dále jsem upravil výběr užitých senzorů a přidal jsem k jednotlivým odesílaným hodnotám značky pro rozpoznávání, ze kterých to vlastně senzorů přicházejí.
Zakládám referenční příručku na wiki, která bude obsahovat detailnější informace o přenosech a podobných záležitostech.

**Comment by Thoronir42** [comment]
Základní čtecí a odesílací smyčka funguje, je ještě třeba odladit a vyzkoušet všechny senzory.
