### ISSUE TITLE
Oprava vypínání senzorů

### ISSUE THREAD

**Issue by vairad** [vairad/zcu-zswi#18]
Pokud se za běhu smyčky vypne nějaký senzor pomocí "D X", kde x je písmeno senzoru ... Senzor se vypne, dle požadavku, ale nefunguje snímání akcelerometru (jediný zkoušený)
namísto A (1-6) se zobrazuje A83

**Comment by vairad** [comment]
Jak jsme na tom?

**Comment by Thoronir42** [comment]
Kód týkající se vypínání senzorů i vypisování hodnot byl několikrát kompletně přepsán, chyba nebyla pozorována, předpokládám že je vyřešena
