### ISSUE TITLE
Volba senzorů

### ISSUE THREAD

**Issue by vairad** [vairad/zcu-zswi#25]
Při zběžném testování jsem přišel na to, že se informace o zvolených senzorech nepropaguje z nastavení do menu aplikace... (a naopak)

Očekávané chování:
V nastavení si vyberu jaké senzory chcu. Tytéž senzory by měli být vybrány i v menu po ukončení nastavení.

Chování aplikace:
Jak v menu, tak v Nastavení > Volba senzorů si lze vybrat zobrazované senzory ( vše OK).
Jen se informace o zvolených nepropaguje mezi menu a nastavením. 
Tzn. Mám zašktrnuto něco jiného než se opravdu zobrazuje.

![chybka_volba_senzoru](https://cloud.githubusercontent.com/assets/8919044/6887216/4dd6e0ea-d658-11e4-93e8-4472ea7a4433.png)

**Comment by jarosdavid** [comment]
Zvolené senzory v menu Zobrazit by se již měly i po změnách shodovat s checkboxy v nastavení. Před zavřením ještě otestovat.

**Comment by vairad** [comment]
V poslední verzi vše funguje dle očekávání.
