### ISSUE TITLE
Autorství arduino app

### ISSUE THREAD

**Issue by vairad** [vairad/zcu-zswi#26]
Bylo by hezké přidat spoluautorství a revidovat celý úvodní komentář do naší smyčky k Arduinu.

**Comment by Thoronir42** [comment]
Upravil jsem úvodní komentář do jakési takové podoby, která by teoreticky mohla říci nově příchozímu programátorovi "vo co go".

**Comment by vairad** [comment]
Myslím, že je to dostatečné.
