### ISSUE TITLE
Frekvence zpráv z Arduina

### ISSUE THREAD

**Issue by vairad** [vairad/zcu-zswi#29]
Je třeba vymyslet, jak rychle je třeba snímat a odesílat data z arduina do PC a připravit na to smyčku.

**Comment by Thoronir42** [comment]
Smyčka je prozatím nastavena na deset cyklů za vteřinu.. je třeba otestovat snímané údaje

**Comment by Thoronir42** [comment]
Testováním se ukázalo, že je ideální 50 měření za sekundu, tato hodnota je v arduinu nyní nastavená
