### ISSUE TITLE
PulsOximeter

### ISSUE THREAD

**Issue by vairad** [vairad/zcu-zswi#31]
Pulsoxi meter pravděpodobně posílá nějaký bordel na sériový port... Protože pokud je aktivní, tak smyčka vrací "Neplatny prikaz-argument!"
A z té mé konzolové aplikace nejde ovládat senzory.

**Comment by Thoronir42** [comment]
Pohrál jsem si s kódem, který se stará o přijímání zpráv ze sériového portu. Nevím však ale, jestli to vyřeší stávající problém.

**Comment by Thoronir42** [comment]
Pulsioximetr používal proměnnou, která byla používána právě pro zpracovávání příkazů, vyřešeno
