### ISSUE TITLE
Validace dat EKG

### ISSUE THREAD

**Issue by vairad** [vairad/zcu-zswi#32]
V repozitáři jsou nová nepřesná data EKG ... (Nemám doma nalepovací konce)

Otázka zní mohou to být správné hodnoty?

**Comment by denitara** [comment]
Ano, ty hodnoty vypadají rozumně... tedy asi tak jedna z 10. Ty ostatní se mi, nevím proč, zobrazují jako datum (např. I.5448 - > když na to kliknu, tak to ukazuje 1.1.5448, děje se Ti to taky?), ale když pominu tu jednu tečku a řeknu si, že to má znamenat 1,15448, tak to pořád dává smysl... :-D mělo by to ukazovat hodnoty 0-5, což ukazuje... :-)

**Comment by denitara** [comment]
Tak jsem si to zobrazila v Notepadu a předchozí problém již není, čas od času je ta hodnota trochu divná (např. 2.35.8915), ale to hooodně zřídka :-D Každopádně jsem si to nakreslila do grafu a přijde mi to stále podivné... vidím tam jen jednu vlnu (nahoru -> dolů, zřejmě komplex QRS), která se přibližně stejně opakuje... Nic mezitím, žádné P, žádné T, žádné U... Takto by se řetězec sestával ze dvou znaků (a - nahoru, b - dolů)... a to je blbost :-D

**Comment by vairad** [comment]
Kluci včera (8.4.) naměřili nová data. Tak si je zkus projít. :)

**Comment by denitara** [comment]
Data jsou OK :-) Moc děkuji.
