### ISSUE TITLE
Efektivnější formát odesílání hodnot z arduina

### ISSUE THREAD

**Issue by Thoronir42** [vairad/zcu-zswi#33]
Již dříve jsem zmiňoval, že je vskutku nadbytečné posílat v každé zprávě u každé hodnoty i popisek, co je to za hodnotu.. Napadlo mě proto, že by se při změně mohlo Ino poslat jen popisky měřených senzorů, např [A, H, R, P, F] a poté by posílalo jen hodnoty v uvedeném pořadí. Pro kontrolu by se u změny mohl poslat klíč,například znak, který by se posílal u každé sestavy naměřených hodnot... Desktop by si tento klíč pamatoval a kdyby došlo ke změně, kterou by Desktop nezaregistroval, mohl by si o popisky zažádat znovu..

**Comment by vairad** [comment]
Mě se to líbí. Je to vcelku rozumné.
Ale není to něco, co bychom měli mít teď.... Momentálně je třeba propojit GUI a Arduino po vzduchu.

**Comment by Thoronir42** [comment]
Práci na tomto formátu zmrazuji (a přesouvám do složky ../arduino/rozsypanyCaj). Založil jsem nový soubor obsahující ještě lehčí smyčku.
