### ISSUE TITLE
Chování detailních oken

### ISSUE THREAD

**Issue by vairad** [vairad/zcu-zswi#34]
Detailní okno jde spustit kliknutím na malý graf...
Když už ale okno zobrazené je klik se tváří, jakoby nefungoval. (Okno už je totiž vytvořené, jen je v pozadí)

Cíl: Reagovat na kliknutí na malý graf vždy... Buď vytvořím okno nebo ho posunu do popředí.

**Comment by jarosdavid** [comment]
Opraveno, ještě otestovat.

**Comment by vairad** [comment]
Cajk
