### ISSUE TITLE
Akce clear

### ISSUE THREAD

**Issue by vairad** [vairad/zcu-zswi#35]
V GUI postrádám nějakou akci, která vyčistí grafy senzorům. 
Respektive, co se stane, pokud mám dlouhá data. Začnou se přepisovat od začátku?

Je třeba specifikovat a implementovat chování.

**Comment by jarosdavid** [comment]
Akce přidána.

**Comment by vairad** [comment]
Nevidím problém ve faktické implementaci. Jen se bojím, že jsem si to dopředu moc nerozmyslel.
Protože teď mě napadá otázka: Jak asi ta aplikace bude používána (PROMOTION):
* posadím si tam člověka
* začnu ho měřit
* hezky se to hýbe
* skončím měření
* připnu dalšího 
* tak to vyčistím
* začnu měřit
* ....

Mám pocit, že by sneslo tohle tlačítko globalizovat. I pro všechny senzory.

**Comment by vairad** [comment]
Jen ta paměť.
Proto to tady nechám strašit. Graficky je reakce správná.

**Comment by vairad** [comment]
Davide výborná práce... 
Jen mě mrzí, že jsem se snažil dělat to samé... :/

**Comment by jarosdavid** [comment]
Ještě jsem něco opravil, ale pořád nám něco někde uniká. Zkus si načíst soubor pomocí *Soubor > Otevřít*, i když se křivka vykreslí a soubor zavře (předpokládám, že se zavře), neuvolní se poměrně dost paměti...

**Comment by vairad** [comment]
Co považuješ za poměrně dost? ... Ty soubory mají kolem 30kB ... (Ty delší až 100kB), což není moc dobře vidět... Udělám si nějaký delší.

**Comment by jarosdavid** [comment]
Po spuštění aplikace na celou obrazovku mi zabírá cca 12 MB paměti, po vykreslení celého souboru *ekg.dat* do grafů je paměť na necelých 15 MB. Když ale grafy vyčistím, uvolní se asi jen 0,7 MB místo zhruba 3 MB. Nejvíc se ale paměť ztrácí při načtení souboru pomocí *Soubor > Otevřít*, jen při otevření stejného souboru *ekg.dat*, který má 22 kB, přijdeme asi o 12 MB, které se nikdy neuvolní... Pokud takhle otevřu několik souborů, už to zase utíká do stovek MB.
