### ISSUE TITLE
Přepisování grafů

### ISSUE THREAD

**Issue by vairad** [vairad/zcu-zswi#36]
Chceme následující chování všech grafů:

délka (osa x) grafu v modulu promotion je dána časem pro každý senzor různý
* záznam EKG chceme zobrazit cca 30 period ... což je cca 30s a po tomto čase se začne křivka přepisovat od začátku plátna

v modulu science jde křivka rolovat a má detailněji popsanou časovou osu.

**Comment by vairad** [comment]
Osa je pevná, jen obsah se chová stále stejně.
Otázka je to v řešení?

**Comment by jarosdavid** [comment]
Pracuji na tom :-)

**Comment by jarosdavid** [comment]
Graf by se již měl vykreslovat správně a respektovat konstantní délku osy x. Mělo by fungovat i přepisování. Pro testování jsem vytvořil nový soubor ekg2.dat s upraveným Štěpánovo EKG, jelikož ten původní s 1500 hodnotami odpovídal 30 s a přepisování by tak nebylo vidět.

**Comment by vairad** [comment]
Nerozpoznávám přepisování...
Co je ale horší... Zvětšené okno jde roztahovat, ale samotná křivka v něm zůstává stejná.

**Comment by jarosdavid** [comment]
Nevím, co jsi provedl, ale i ve zvětšeném okně se mi křivka bez problému roztahuje dle délky osy x. Stejně tak i přepisování je celkem dobře znatelné na upraveném Štěpánovo EKG ekg2.dat.

**Comment by vairad** [comment]
Omlouvám se... pravděpodobně jsem jen něco nepřeložil... Teď vše funguje a neumím stav navodit znovu
