### ISSUE TITLE
Meze senzorů

### ISSUE THREAD

**Issue by vairad** [vairad/zcu-zswi#37]
Je třeba kouknout do medicíny (možná stačí dokumentace cooking hacks) a zjistit nějaké mezní hodnoty senzorů a doplnit je k jednotlivým implementacím.

Jde o hodnoty maxY a minY.

**Comment by jarosdavid** [comment]
Kromě mezních hodnot je třeba doplnit i jednotku zobrazované veličiny (atribut unit).
