### ISSUE TITLE
Oximetr nevrací žádné hodiny

### ISSUE THREAD

**Issue by Thoronir42** [vairad/zcu-zswi#39]
Narazil jsem na zádrhel, že funkce na získání míry okysličení vrací vždy 0. Pro ověření chyby jsem použil demonstrační kód z cooking hacks.
Možné příčiny jsou
* Poškození metru
* Poškození zařízení

**Comment by vairad** [comment]
Zkusili jsme obě Ina i oba oxy-metry ?

**Comment by Thoronir42** [comment]
Testoval jsem všechny kombinace obou zařízení s oběma oximetry a vždy vycházela hodnota nulová. Předpokládám, že poškození není ani v jedné z těchto součástí systému a že je jen špatně napsaná eHealth.h.
