### ISSUE TITLE
Oprava vedlejších os u zobrazení okysličení

### ISSUE THREAD

**Issue by denitara** [vairad/zcu-zswi#41]
Když jsem změnila ty meze, tak u grafu pro okysličení se vedlejší (pomocné) osy dost zhustily, takže tím pádem moc pomocné nejsou... :-)
Koukněte prosím na to...

**Comment by jarosdavid** [comment]
Opraveno :-), ještě před zavřením prosím zkontrolovat.

**Comment by vairad** [comment]
Je třeba mít u oxymetru rozsah 100% ... protože mám pocit, že s člověka s nulou už měřit nebudeme... :)

Hodilo by se zamyslet se i nad pravděpodobností získání té které hodnoty.

**Comment by denitara** [comment]
Možná bychom mohli zvýraznit část úseku, kdy jsou hodnoty "normální".  Ta nula je asi vážně zbytečná. V našich poměrech (nadmořská výška apod.) to budou hodnoty 95-98(99)%, u osob s problémy s dýcháním je to kolem 88-94%. S větší nadmořskou výškou a s fyzickou zátěží hodnota klesá, pod 50% už dochází k bezvědomí...

**Comment by denitara** [comment]
Nastavila jsem minimální hodnotu na 75%, poprosím znovu o úpravu těch vodorovných vedlejších os, které tam teď zcela chybí... :-) Díky
