### ISSUE TITLE
Kdy se ukládají data?

### ISSUE THREAD

**Issue by vairad** [vairad/zcu-zswi#42]
Ve snaze, rychle otestovat načítání senzorů ze souboru metadat jsem zjistil že nevím:
* kdy se metadata ukládají
* jak toto načítání senzorů má fungovat (k čemu přesně slouží)

Děkuji za odpověď

Plus jsem v rychlosti postrádal nějakou akci na vyvolání uložení dat...

**Comment by jarosdavid** [comment]
Ukládání a načítání metadat zatím připravuji na úvodní okno, které by se bez toho neobešlo. Ukládání metadat lze zatím testovat po otevření uživatelského nastavení a stisknutí OK. Soubor s metadaty se uloží do složky s uživatelským jménem ve složce *build*. Načítání zatím nelze z GUI testovat, ale mělo by se provést zavoláním metody *getMetadata* ve třídě *DataManager*. Tato metoda bude volána se zvoleným uživatelským jménem po kliknutí na vybraného pacienta v úvodním okně.

**Comment by vairad** [comment]
Super, tak to zatím necháme uležet. A ty vytvoříš ticket až to bude možné otestovat.
