### ISSUE TITLE
transmitData()

### ISSUE THREAD

**Issue by vairad** [vairad/zcu-zswi#44]
Mám dvě věci. 

* Původně jsem myslel, že to bude brát řádky postupně z nějakého listu samo od sebe. Takhle to asi nevadí. 

* Máš ošetřenou tu hranatou závorku na začátku a konci?

**Comment by Eflyax** [comment]
Nevím, jestli to brát z listu, taky si myslím, že to takhle stačí. Závorky ošetřené jsou. Hodlám ještě ošetřit převod na číslo.

**Comment by vairad** [comment]
Zase dvě věci :) ... Teď je to +/-. Snad...

* QString má spoustu metod toDouble() ... takže tam asi najdeš co potřebujeme a není moc co ošetřovat (myslím)
* Špatný řádek se pozná až tady a nebo někde před?
