### ISSUE TITLE
Změna místa ukládání metadat

### ISSUE THREAD

**Issue by vairad** [vairad/zcu-zswi#46]
Prosímtě nelze změnit umístění metadat ve vstupním dialogu. (Myslím, že pole je disabled) 

Textové pole ukazuje na C:/metadata.txt, kam logicky metadata ukládat nechci.

Mohl by si se zaměřit na změnu tohoto umístění? 
Díky

**Comment by jarosdavid** [comment]
Do umístění *C:/metadata.txt* se nikdy nic neukládá. Metadata se ukládají vždy do *\<cesta do build>/data/\<username>/metadata.txt*. To *C:/metadata.txt* tam vznikalo proto, že u právě registrovaného uživatele není ještě známo to *username* a dělalo to bordel. Teď se už v takovém případě pole nezobrazí vůbec. Změnu umístění bych nechtěl provádět tímto způsobem, ale už dříve, nejlépe v úvodním okně, kde by se zvolil jakýsi workspace. Po jeho zvolení by se zobrazili uživatelé, kteří by už ve složce měli svá data. A další registrovaní uživatelé by se uložili právě do té samé složky. To je moje představa, ale kdybys měl lepší nápad, stačí navrhnout :-)

**Comment by vairad** [comment]
Ne tenhle návrh se mi líbí a přijde i logicky umístěný.
A děkuji za rychlou reakci.

**Comment by vairad** [comment]
Funguje bez výhrad.
