### ISSUE TITLE
Výber uživatelů

### ISSUE THREAD

**Issue by vairad** [vairad/zcu-zswi#57]
Bavili jsme se o tom mít dva možné způsoby výběru uživatelů.

1) konstantní počet nedávno otevřených
2) abecední seznam nalezených v dané složce

**Comment by vairad** [comment]
Na mém stroji se nyní neaktualizují pozice prvních tří. Jako poslední zobrazí první tři složky.
Zkoušel jsem i vytvořit nový workspace. (v domnění, že jsem starý špatně inovoval)

 (I když mám pocit, že jsem to ve čtvrtek viděl fungovat).

Myslím, že bude snazší, když koukneš na zdroj než abych hledal revizi, kde to funguje.

Každopádně priorita je úkolu je nízká.

**Comment by vairad** [comment]
Ještě jsem se špatně vyjádřil.
Problém je jen v seznamu posledních otevřených. A to jen ve výběru posledních.

Abecední seznam funguje tak jak bych očekával.

**Comment by jarosdavid** [comment]
Omlouvám se, do včerejška to opravdu fungovalo. Chyba byla zanesena změnou struktury metadat z důvodu přidání nastavení, zda chce uživatel ukládat data. Už by mělo být vše v pořádku.
