### ISSUE TITLE
Název aplikace

### ISSUE THREAD

**Issue by jarosdavid** [vairad/zcu-zswi#63]
Je potřeba vymyslet vhodný (výstižný a krátký) název naší desktopové aplikace. Název bude zobrazen jak v titulku hlavního okna, tak i v úvodním okně po spuštění.

**Comment by denitara** [comment]
Napadlo mě, že by to mohlo končit příponou -ino ...aby to vyjádřilo, že to pracuje s Arduinem... :-)

**Comment by denitara** [comment]
Napadla mě taková blbost... Biodatino :-D

**Comment by denitara** [comment]
Co třeba Šejdrem Sensor? A v ikonce by bylo ŠS v srdíčku :-D

**Comment by Eflyax** [comment]
Mě napadlo "HealthMiner"
