### ISSUE TITLE
Doplnit label do AnalysisWindow

### ISSUE THREAD

**Issue by denitara** [vairad/zcu-zswi#67]
Prosím o doplnění labelu do AnalysisWindow, který bude ukazovat, z kolika procent je srdeční rytmus pravidelný (metoda getRegularityPercentage v Analyseru)...

**Comment by jarosdavid** [comment]
Label jsem přidal a zároveň trochu zpřehlednil okno díky dvousloupcovému zobrazení. Může to takto být? :-)
