### ISSUE TITLE
Testování zadavatelem

### ISSUE THREAD

**Issue by denitara** [vairad/zcu-zswi#70]
Nechat zadavatele otestovat aplikaci...

**Comment by Thoronir42** [comment]
viz #51 ?

**Comment by denitara** [comment]
No, v podstatě... v #51 šlo o to mu ukázat, co máme... :-) Nesmíme ale zapomenout mu to půjčit "do ruky", aby si sám všechno vyzkoušel, jestli všemu rozumí, jestli je pro něj umístění tlačítek pohodlné a podobně...
